default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: action_cable_test_development
test:
  <<: *default
  database: action_cable_test_test
production:
  <<: *default
  database: action_cable_test_production
  password: <%= ENV['ACTION_CABLE_TEST_DATABASE_PASSWORD'] %>
